import eslint from '@eslint/js';
import eslintConfigPrettier from 'eslint-config-prettier';
import eslintPluginAstro from 'eslint-plugin-astro';
import eslintPluginSvelte from 'eslint-plugin-svelte';
import tseslint from 'typescript-eslint';

import parserAstro from 'astro-eslint-parser';
import parserSvelte from 'svelte-eslint-parser';

import globals from 'globals';

import svelteConfig from './svelte.config.js';

export default tseslint.config(
  {
    ignores: [
      '**/.DS_Store',
      '**/node_modules',
      'build',
      'dist',
      '.svelte-kit',
      'package',
      '**/.env',
      '**/.env.*',
      '!**/.env.example',
      '**/pnpm-lock.yaml',
      '**/package-lock.json',
      '**/yarn.lock',
      'src/env.d.ts', // auto generated by astro
    ],
  },
  eslint.configs.recommended,
  eslintConfigPrettier,
  ...eslintPluginSvelte.configs['flat/recommended'],
  ...tseslint.configs.recommended,
  ...eslintPluginAstro.configs.recommended,
  {
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },

    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },

      parser: tseslint.parser,
      ecmaVersion: 2020,
      sourceType: 'module',
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          varsIgnorePattern: '^_',
          argsIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    files: ['tests/**/*.ts'],

    languageOptions: {
      parser: tseslint.parser,
      ecmaVersion: 5,
      sourceType: 'script',

      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },

    rules: {
      'require-await': 'off',
      '@typescript-eslint/require-await': 'error',
      'svelte/no-inner-declarations': 'off', // FIXME: for some reason this rule is broken and causes eslint to crash
    },
  },

  {
    files: ['**/*.astro'],

    languageOptions: {
      parser: parserAstro,
      ecmaVersion: 5,
      sourceType: 'script',

      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: ['.astro'],
      },
    },
  },

  {
    files: ['*.svelte', '**/*.svelte'],

    languageOptions: {
      parser: parserSvelte,
      parserOptions: {
        parser: tseslint.parser,
        svelteConfig,
        extraFileExtensions: ['.svelte'],
      },
    },
  },
);
