name: autofix.ci
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install Node Dependencies
        run: pnpm install
      - run: pnpm run format
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
